"""Make user_id nullable in tts_history for channel posts

Revision ID: 5a8cbfafa7c9
Revises: 967d5c456596
Create Date: 2026-01-21 14:15:44.932823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8cbfafa7c9'
down_revision: Union[str, None] = '967d5c456596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tts_history', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tts_history', 'original_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tts_history', 'processed_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'tts_history', 'chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tts_history', type_='foreignkey')
    op.alter_column('tts_history', 'processed_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tts_history', 'original_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tts_history', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
